name: Automatic integration-examples Release

on:
  push:
    branches:
      - main

jobs:
  github-release:
    name: Bump version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Initial commit')"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.CI_PAT_TOKEN }}