name: Build integrations-examples docker service

on:
  push:
    tags:
      - "**"

env:
  GCP_REPO: europe-west2-docker.pkg.dev/tooling0x/onebalance/onebackend/integration-examples

jobs:
  build-integrations-examples:
    runs-on: onebalance-runner
    timeout-minutes: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: "0"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "configure GCP docker registry"
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create latest tag
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$GCP_REPO:latest" >> $GITHUB_ENV

      - name: Create docker tag for ${GITHUB_REF#refs/*/}
        run: |
          if [[ -n $DOCKER_TAG ]]; then
            TAG_PREFIX="$DOCKER_TAG,"
          fi
          echo "DOCKER_TAG=$TAG_PREFIX$GCP_REPO:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./privy
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAG }}
          provenance: false
